mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('add', views.add, name='add'),
    path('new', views.new, name='new')
]

polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete = models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text
 

polls/views.py
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from .models import Question, Choice 
from django.utils import timezone
from django.contrib import messages

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {
        'latest_question_list': latest_question_list,
    }
    return render(request,'polls/index.html',context)

def detail(request,question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def add(request):
    context = {}
    return render(request, 'polls/add.html', context)

def new(request):
    tmp = ""
    if request.method == 'POST':
        question = request.POST.get('question')
        choice1 = request.POST.get('choice1')
        choice2 = request.POST.get('choice2')
        choice3 = request.POST.get('choice3')
        choice4 = request.POST.get('choice4')
        question_object = Question.objects.create(question_text=question,pub_date=timezone.now())
        question_object.choice_set.create(choice_text=choice1,votes=0)
        question_object.choice_set.create(choice_text=choice2,votes=0)
        question_object.choice_set.create(choice_text=choice3,votes=0)
        question_object.choice_set.create(choice_text=choice4,votes=0)
        tmp = "Poll Created Successfully!!"
    else:
        tmp = "Some Error Occured!!"
    messages.add_message(request,messages.INFO,tmp)
    return HttpResponseRedirect(reverse('polls:add'))
        

polls/templates/polls/add.html
{% extends 'polls/base.html' %}
{% block content %}
<div class="container justify-content-center down" >   
    <form action="{% url 'polls:new' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="question">Question</label>
            <input name="question" type="text" class="form-control" id="question">
        </div>
        <div class="form-group">
            <label for="choice1">choice 1</label>
            <input name="choice1" type="text" class="form-control" id="choice1">
        </div>
        <div class="form-group">
            <label for="choice2">choice 2</label>
            <input name="choice2" type="text" class="form-control" id="choice2">
        </div>
        <div class="form-group">
            <label for="choice3">choice 3</label>
            <input name="choice3" type="text" class="form-control" id="choice3">
        </div>
        <div class="form-group">
            <label for="choice4">choice 4</label>
            <input name="choice4" type="text" class="form-control" id="choice4">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock content %}

polls/templates/polls/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Polls App</title>
  </head>
  <body>
    {% block navbar %}
    {% include 'polls/navbar.html' %}
    {% endblock navbar %}
    {% block content %}
    <h1> No Content To Show Here!! </h1>
    {% endblock content %}
    {% load static %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

polls/templates/polls/detail.html
{% extends 'polls/base.html' %}
{% block content %}
<div class="container">
    <div class="jumbotron"><h1 class="display-4">{{ question.question_text }}</h1></div>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        <ul class="list-group">  
        {% for choice in question.choice_set.all %}
        <li class="list-group-item">    
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
        </li>
        </ul>
        <br>
        <input type="submit" class="btn btn-primary" value="Vote">
    </form>
</div>
{% endblock content %}

polls/templates/polls/index.html
{% extends 'polls/base.html' %}
{% block content %}
<div class="container">    
    {% if latest_question_list %}
        {% for question in latest_question_list %}
        <div class="row dabba">
            <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
        </div>
        {% endfor %}
    {% else %}
    <h3>No polls are available.</h3>
    {% endif %}
</div>
{% endblock content %}

polls/templates/polls/navbar.html
{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">POLLING</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'polls:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'polls:add' %}">Add</a>
        </li>
      </ul>
      <span class="navbar-text">
      </span>
    </div>
  </nav>
  {% if messages %}
    {% for message in messages %}
    <div class="alert alert-success" role="alert">
      {{ message }}
    </div>
    {% endfor %}
  {% endif %}
  {% endblock navbar %}

polls/templates/polls/results.html
{% extends 'polls/base.html' %}
{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1 class="display-4">{{ question.question_text }}</h1>
    </div>
    <ul class="list-group">
        {% for choice in question.choice_set.all %}
        <li class="list-group-item">{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>
    <br>
    <a  class="btn btn-success" href="{% url 'polls:detail' question.id %}">Vote again?</a>
</div>
{% endblock content %}